### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by tecosaur** [RuleBasedIntegration/Rubi-5#2]
Hello,

With the last public update to this repo being over a year ago, it would be great to hear if this is still actively being worked on :slightly_smiling_face:.

**Comment by AlbertRich** [comment]
Yes, Rubi 4 is currently undergoing a major redesign that will significantly expand the class of mathematical expressions it can integrate, produce simpler antiderivatives, and provide more elegant derivations.  Also it is necessary to perfect Rubi 4 _before_ compiling its pattern matching rules into an if-then-else decision tree for the next release of Rubi.

I'm working fulltime on what has turned out to be a massive project.  It's driven by my figuring out the math required to integrate expressions symbolically.  I will release a new version of Rubi 4 as-soon-as it's perfected to my satisfaction.  But it's impossible to predict when that will be, given the creative nature of this open-ended work.

Albert

**Comment by tecosaur** [comment]
Thanks for the update Albert! It's great to hear things are still ticking along.
